### ISSUE TITLE
Adding custom nodes

### ISSUE THREAD

**Issue by mick-d** [GiraffeTools/GiraffeTools#107]
It would be great to be able to use custom nodes, imported automatically from python files containing NiPype workflows and nodes.

Maybe this is already possible in porcupine?

**Comment by mdlm199** [comment]
I agree with the opinion of mick-d, it would be nice to have a tool that imports custom nodes ( or workflow or class). Maybe it exists as you have you already all the nipype nodes into json files.

**Comment by TimVanMourik** [comment]
Hi @mick-d, @mdlm199, I totally agree and it's definitely part of the plan. I just did rewrote the back-end to lay the groundworks for this and make it possible. In the original Porcupine version we [made this possible](https://timvanmourik.github.io/Porcupine/documentation/advanced/custom-nodes). 

I'm still thinking about the best way to facilitate this. I would like to be able to grab the functions from a repository. I would like a to add a field to the [GIRAFFE.yml](https://github.com/TimVanMourik/SomeGiraffeExample/blob/master/GIRAFFE.yml) that points to a Python file that needs to be loaded in as a module. Not completely sure about the specifics yet. Have you got any suggestions? What would be your preferred way of importing custom modules?

**Comment by mdlm199** [comment]
Thanks for your answer @TimVanMourik. I'm happy to hear that it's part of the plan, as it will allow people to share their work and even extend the use of giraffetools to other fields.
I think  one of the best asset of giraffetools is that it is easy to use even for non-programmer. If you want people to be able to add custom nodes, you should ensure that a node A from guy 1 is compatible with node B of guy 2. For that, I think custom nodes should be written the nipype (see attached file, where I rewrote your porcupine custom function exemple). It may force people to specify inputs and outputs types and may be more convenient for documentation and description.

![Screenshot from 2019-03-11 09-51-30](https://user-images.githubusercontent.com/28844486/54111116-6739f700-43e3-11e9-821c-f2e732c43130.png)

**Comment by TimVanMourik** [comment]
Yes, I agree, @vferat, that the new functionality should be compatible with Nipype workflows that are currently generated. My current idea is as follows:


* [ ] The current repository needs to be imported in the Dockerfile
  * `RUN git clone https://github.com/User/Repo`
  * The tricky thing here is that if the source repository has its own dependencies, these are not installed. Unless we force the user to list them in a `requirements.txt` and install that one, if it exists.
* [ ] The code will either have to be present in a predetermined file or in a dynamic file as listed in the GIRAFFE.yml file in the root directory. I prefer the latter. Something like this:
```
tools:
  porcupine:
    file:
      - GIRAFFE/porcupine_pipeline.pork
    nodes:
      - GIRAFFE/customNodes.json
```
* [ ] At this point the website can just probe the `GIRAFFE/customNodes.json` files and display them in the editor. In this solution, the user has to create this file, so we need to present a clear-cut way of creating it. The file that you're mentioning is a pretty good start :+1:
* [ ] The code needs to be imported in the Python script like:
  * `from .this.repository import NewInterface`

What do you think, @vferat, @mick-d, do you think that's a useful approach?

**Comment by TimVanMourik** [comment]
Almost there, @mick-d @vferat! Just implemented number 2, which was by far the hardest part. I just made work an entire custom toolbox that I wrote for laminar analysis: https://giraffe.tools/porcupine/TimVanMourik/OpenFmriAnalysis

If the toolbox were Nipype compatible it would actually produce code, but that's not the case here. The rest will be implemented soon

**Comment by vferat** [comment]
Hi @TimVanMourik ,

Sorry to answer so lately , got a lot of work this weeks. Your solution looks like exactly what I expected, this would surely be a game changer feature for giraffetools !

- For answering your previous message, I think writting a `requirements.txt` should be a good solution, it is not so complicated for contributors and would be easly implemented in giraffe.tools
Anoter solution may be to deploy the custom repo to Pypi and installing it with `pip install.`
Problem may arise if 2 customs repositories import different version of a same python librairy (i.e sklearn, numpy... ), this may interfer in the docker image.

- What do you mean by "Nipype compatible" ? I have some exemples written such as my last comment that should do the work for testing.

- Do you have an exemple on how to create the `GIRAFFE/customNodes.json` file and add it to giraffe.tools ?


Thanks for all your work, If you need I would be happy to help you a way or another.

**Comment by mick-d** [comment]
@TimVanMourik this looks fantastic! 

For creating the json file, do you already have some code inferring it from a NiPype interface InputSpec and OutputSpec?

**Comment by TimVanMourik** [comment]
Hi @vferat, quick answer to your questions:
* Alright, I'll start out with the `requirements.txt` as an initial solution and we'll see if it needs to be updated. 
* With nipype compatible I mean that my toolbox is written in MATLAB and doesn't have nipype wrapper yet. So in the current exmple there is no functional code produced. 
* The example of creating custom nodes for my old stand-alone Porcupine is (here)[https://timvanmourik.github.io/Porcupine/documentation/advanced/custom-nodes], but I still need to update it to be compatible with GiraffeTools. WIP. 

@mick-d, thanks! At this moment I have code to automatically makes nodes from nipype in its entirety in https://github.com/TimVanMourik/GiraffeTools/tree/master/utilities, but not specifically from the  InputSpec and OutputSpec. I'll try and work on that some time soon! Hopefully before OHBM, but I'm defnitely up for discussing this further in Rome!

**Comment by mick-d** [comment]
@TimVanMourik sounds great!

@vferat and I are actually collaborating so we can both help you in some aspects. We will probably start focusing first on importing custom nodes. Do you have any insight on how best combining efforts for this?

I imagine the steps would be to:
- creating custom nodes similar to NiPype's (we already have some at our ends)
- adapt [parse_nipype.py](https://github.com/TimVanMourik/GiraffeTools/blob/master/utilities/parse_nipype.py) to parse these custom nodes (it does not seem too difficult, anything in particular we should be aware of?) and dump them in a customNodes.json file
- <post-magic to implement to have them read by Giraffe?> (just put `customNodes.json` in `GIRAFFE/`? The master branch can already deal with this?)

**Comment by TimVanMourik** [comment]
Ah, that's good to know! Let's see, basically that `parse_nipype` script is indeed basically exactly the what needs to be adapted. The `node2json` function is critical here and basically takes in any Nipype node. 

Something you gotta be aware of is that all nodes need to be wrapped in a `toolboxes` struct as you can see in the last `json.dump` line. If you want to see what the full JSON structure looks like, check out: 
https://jsoneditoronline.org/?url=https%3A%2F%2Fgiraffe.tools%2Fapi%2Fnodes

If your own library file follows this structure and if that file is referenced in the GIRAFFE.yml file in the `nodes` field ([example](https://github.com/TimVanMourik/OpenFmriAnalysis/blob/master/GIRAFFE.yml)), it *should* all run out of the box!

So in answer to your last question, yes, that's implemented!

**Comment by TimVanMourik** [comment]
Closing this issue as it's working and tested with Nipype and even non-Nipype toolboxes, like: 
https://giraffe.tools/porcupine/TimVanMourik/keras-giraffetools-digit-recognition
