### ISSUE TITLE
github connection

### ISSUE THREAD

**Issue by mlueckel** [GiraffeTools/GiraffeTools#166]
Hi Tim,

thanks for the great tool!

However, I don't seem to be able to properly login/connect with my github. Whenever I try to login, I am redirected to the main page. And when trying so save the workflow, an error occurs ("Sorry, something went wrong there..."). Any idea why that is?

-Max

**Comment by TimVanMourik** [comment]
Hi @mlueckel, it seems you tried to log in at a time that the GitHub connection token had expired. I renewed it and it should work now.
